name: authelia

networks:
  auth:
    name: auth
  smtp:
    external: true
  proxy:
    external: true

services:
  server:
    image: authelia/authelia
    restart: unless-stopped
    volumes:
      - ./config:/config
    ports:
      - 9091:9091
    healthcheck:
      disable: true # In production the healthcheck section should be commented.
    environment:
      - TZ=Mexico/Monterrey
    networks:
      auth:
      smtp:
      proxy:
      default:
    logging:
      driver: 'local'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`auth.homelab.com`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=9091"
      - "traefik.http.middlewares.authelia.forwardAuth.address=http://authelia-server-1:9091/api/verify?rd=https%3A%2F%2Fauth.homelab.com"
      - "traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email"

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ./redis:/data
    networks:
      - default
    expose:
      - 6379
    environment:
      - TZ=Mexico/Monterrey
    logging:
      driver: 'local'
